# -*- coding: utf-8 -*-
"""Contact Book App.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12v6tvzAYM8v21TXB8dhhr7JFRigyW8MI
"""

#Creating the Contact database

contacts = {}

while True:
  print('\n Contact Book App')
  print('1. Create Contact')
  print('2. View Contact')
  print('3. Update Contact')
  print('4. Delete Contact')
  print('5. Search Contact')
  print('6. Count Contact')
  print('7. Exit')

  choice = input('Enter your choice: ')

  if choice == '1':
    name = input('Enter name: ')
    if name in contacts:
      print('Contact already exists')
    else:
      mobile = input("Enter the Mobile Number =  ")
      email = input("Enter the Email =  ")
      relation = input("Enter the Relation =  ")
      contacts[name] = {'mobile': int(mobile), 'email': email, 'relation': relation}
      print(f'Contact name {name} has been created successfully')

  elif choice == '2':
    name = input("Enter contact name to view = ")
    if name in contacts:
      contact = contacts[name]
      print(f'Name: {name},Mobile: {mobile},email:{email},relation:{relation}')
    else:
      print('Contact not found')

  elif choice == '3':
    name = input('Enter contact name to update =  ')
    if name in contacts:
      mobile = input("Enter the updated Mobile Number =  ")
      email = input("Enter the updated Email =  ")
      relation = input("Enter the updated Relation =  ")
      contacts[name] = {'mobile': int(mobile), 'email': email, 'relation': relation}
      print(f'Contact name {name} has been updated successfully')
    else:
      print('Contact not found')

  elif choice == '4':
    name = input('Enter contact name to delete = ')
    if name in contacts:
      del contact[name]
      print(f'Contact name {name} has been successfully')
    else:
      print('Contact not found')

  elif choice == '5':
    search_name = input('Enter contact name to search = ')
    found = False
    for name,contact in contacts.items():
      if search_name.lower() in name.lower():
        print(f'Found - Name {name},Mobile {contact["mobile"]},Email {contact["email"]},Relation {contact["relation"]}')
        found = True
    if not found:
      print(f'No Contact found in name {name}')

  elif choice == '6':
    print(f'Total contacts in your book: {len(contacts)}')

  elif choice == "7":
    print("Good bye... Closing the program")

  else:
    print("Invalid Number")