# -*- coding: utf-8 -*-
"""Spellchecker.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ctBswW5y1d5x580vjthnX7d47KKagyhb
"""

!pip install pyspellchecker

#Importing the required library
from spellchecker import SpellChecker

#Creating the class
class SpellCheckerApp:
  def __init__(self):
    self.spell = SpellChecker()

  def correct_text(self,text):
    words = text.split()
    corrected_words = []

    for word in words:
      corrected_word = self.spell.correction(word)
      if corrected_word != word.lower():
        print(f'Correcting "{word}" to "{corrected_word}"')
        corrected_words.append(corrected_word)
      return ' '.join(corrected_words)

  def run(self):
    print("\n---Spell Checker---")

    while True:
      text = input('Enter text to check (or type "exit" to quit): ')

      if text.lower() == 'exit':
        print('Closing the program...')
        break

      corrected_text = self.correct_text(text)
      print(f'Corrected text: {corrected_text}')

#Running the app
if __name__ == '__main__':
  app = SpellCheckerApp()
  app.run()

